# --------------------------------------------------
# Commands to run this compose file:
#     - docker-compose -p comp3095-integrated -f docker-compose.yml up -d (if you only want to recreate 1 or just not all images when manually delete in docker desktop and run this)
#     This command will start the containers in detached mode (-d) without rebuilding the images (if they already exist)
#
#     - docker-compose -p comp3095-integrated -f docker-compose.yml up -d --build
#     This command force the rebuild of images, even if the images already exist (option for visual appeal: go to docker desktop and delete images, then they HAVE to be created)
# ------------------------------------------------
services:

  api-gateway:
    image: api-gateway
    ports:
      - "9000:9000"
    build:                                     # Build the image using the Dockerfile in the current directory.
      context: ./api-gateway                   # The context provides the build context.
      dockerfile: ./Dockerfile                 # The dockerfile specifies the name of the Dockerfile to use.
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_JSON: '{"logging":{"level":{"root":"INFO","ca.gbc.apigateway":"DEBUG"}}}'
      # SPRING_APPLICATION_JSON={"logging":{"level":{"root":"INFO","ca.gbc.apigateway":"DEBUG"}}}:
    container_name: api-gateway
    networks:
      - spring

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/integrated/redis/data:/data
      - ./docker/integrated/redis/init/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    container_name: redis
    networks:
      - spring

  redis-insight:      # This is just the GUI - will work without it
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    container_name: redis-insight
    depends_on:
      - redis
    networks:
      - spring

  inventory-service:
    image: inventory-service
    ports:
      - "8083:8083"
    build:
      context: ./inventory-service
      dockerfile: ./Dockerfile
    container_name: inventory-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-inventory/inventory-service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-inventory
    networks:
      - spring

  order-service:
    image: order-service
    ports:
      - "8082:8082"
    build:
      context: ./order-service
      dockerfile: ./Dockerfile
    container_name: order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5432/order-service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-order
    networks:
      - spring

  product-service:
    image: product-service
    ports:
      - "8084:8084"
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  postgres-inventory:
    container_name: postgres-inventory
    image: postgres
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./docker/integrated/postgres/data/inventory:/data/postgres                                # mount the database
      - ./docker/integrated/postgres/service/init/init.sql:/docker-entrypoint-initdb.d/init.sql  # mount the init.sql script
    ports:
      - "5433:5432"
    networks:
      - spring

  postgres-order:
    container_name: postgres-order
    image: postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./docker/integrated/postgres/order/data:/data/postgres   # mount the database
      - ./docker/integrated/postgres/order/init/init.sql:/docker-entrypoint-initdb.d/init.sql  # mount the init.sql script
    ports:
      - "5432:5432"
    networks:
      - spring

  pgadmin: # One pgAdmin is enough to connect to multiple postgres databases
    image: dpage/pgadmin4:9.2
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: pgadmin
    networks:
      - spring

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./docker/integrated/mongo/data/products:/data/db
      - ./docker/integrated/mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod --auth
    networks:
      - spring

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
    networks:
      - spring


# Optional volumes section for persisting data
volumes:
  mongo-db:
    driver: local  # Use local driver from persisting data on the host machine

networks:
  spring:
      driver: bridge   #Bridge network allows isolated communication between containers