# Run with: docker-compose -p <mongo-standalone> -f docker-compose.yml up -d
# Note: The mongo-init.js file only runs once, when initializing a brand-new MongoDB volume.
#       If the database already exists, the script will NOT run again.
# Useful reference: https://robert-askam.co.uk/posts/how-to-connect-mysql-workbench-to-running-mysql-inside-docker
# docker-compose -p mongo-redis-standalone -f docker-compose.yml up -d

services:
  # MongoDB service, the database that will be used by product-service.
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-data/products:/data/db  # The database will persist data here on the host machine.
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: mongodb
    command: mongod --auth  # Ensures MongoDB requires authentication.
    networks:
      - backend

  # Mongo-Express is a web-based MongoDB admin interface to manage MongoDB visually.
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb  # Connect Mongo-Express to the MongoDB container by name.
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    container_name: mongo-express
    depends_on:
      - mongodb
    networks:
      - backend

  redis:
    image: redis:7.4.3
    container_name: redis # Keep serivce name and container name the same as a good practise
    ports:
      - "6379:6379"
    restart: no # Don't want containers to start on their own when you boot up your computer in a Dev environment
    volumes:
      - ./init/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  redisinsight:
    image: redislabs/redisinsight:1.14.0 # Version Prof. Sergio can vouch for
    container_name: redisinsight
    ports:
      - "8001:8001"
    # Thursday version has "restart: no" here too
    depends_on:
      - redis
    networks:
      - backend

# Optional: define a custom bridge network for container-to-container communication
networks:
  backend:
